# Generated by Django 5.0.6 on 2024-06-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userstartedcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '2. Courses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': '4. Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonvideo',
            options={'verbose_name_plural': '5. Lesson Videos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '1. Profile'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': '3. Sections'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'verbose_name_plural': '7. Send messages to users.'},
        ),
        migrations.AlterModelOptions(
            name='userstartedcourse',
            options={'verbose_name_plural': '6. Courses initiated by the user'},
        ),
        migrations.RenameField(
            model_name='usernotification',
            old_name='timestamp',
            new_name='created',
        ),
    ]
