# Generated by Django 5.0.6 on 2024-06-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_usernotification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'verbose_name_plural': '7. Messages sent to users'},
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True),
        ),
    ]
